codeblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('projects/', include('projects_index.urls')),
    path('admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('base/img/favicon.ico'))),
    
    path('youtube-comment-scraper/', include('comment_viewer.urls')),
    path('flight-tracker/', include('flight_tracker.urls')),
    path('covid19-stat/', include('covid19stat.urls')),
    path('code-syntax-highlight/', include('code_syntax_highlight.urls')),
    path('parcel-tracker/', include('parcel_tracker.urls')),
    path('stock-photos/', include('stock_photos_explorer.urls')),
    path('book-catalogue/', include('book_catalogue.urls')),
]

handler404 = 'base.views.http_404_handler'
#handler500 = 'base.views.http_404_handler'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/code_syntax_highlight/urls.py
from django.urls import path
from . import views

app_name = 'code-syntax-highlight'

urlpatterns = [
    path('', views.home, name='code-syntax-highlight'),
    path('get-preview/<str:theme>', views.get_preview, name='get-preview'),
    path('get-formatted-code', views.get_formatted_code, name='get-formatted-code')
]

projects/code_syntax_highlight/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles, get_style_by_name
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import PythonLexer, guess_lexer, get_lexer_by_name
from django.views.decorators.csrf import csrf_exempt

def home(response):
	#preview = (highlight(code, PythonLexer(), HtmlFormatter(full=True, style=i)) for i in get_all_styles())
	return render(response, 'code-syntax-highlight/main.html', {'lexer_list': get_all_lexers(), 'style_list': get_all_styles(), 'preview': get_all_styles(), 'title': 'Code Syntax Highlighter'})


def get_preview(response, theme=None):
	code = '''
#'''+theme+'''

from some_module import some_function
import some_module as module_name

@decorator(param=1)
def f(x):
	""" Syntax Highlight Demo
	@param x Parameter"""
	s = ("Test", 2+3, {'a':'b'}, x) #Comment

class Foo:
	def __init__(self):
		byte_string = 'newline:\\n also newline:\\x0a'
		text_string = u"Cyrillic Я is \\u042f."
		self.makeSense(whatever=1)
		print(some_function())

	def makeSense(self, whatever)
		self.sense = whatever
x = len('abc)
print(f.__doc__)'''
	return HttpResponse(highlight(code, PythonLexer(), HtmlFormatter(full=True, style=theme)))


@csrf_exempt
def get_formatted_code(response):
	if response.POST:
		return HttpResponse(highlight(response.POST['text'], get_lexer_by_name(response.POST['lexer']), HtmlFormatter(full=True, style=response.POST['style'])))

projects/code_syntax_highlight/templates/code-syntax-highlight/main.html
{% load static %}

<!doctype html>
<html>
<head>
	{% include 'base/head.html' %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href='{% static "base/navbar.css" %}'>
	<link rel="stylesheet" type="text/css" href="{% static 'code-syntax-highlight/main.css' %}">
	<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
</head>
<body>
	{% include 'base/navbar.html' %}
	<div class='center-container'>
		<div class='title-container'>
			<h1 class='title'>Code Syntax Highlighter</h1>
			<h3 class='subtitle'>Scroll down for themes preview</h3>
		</div>
		<div class='progress-bar-wrapper'>
			<ul class='progressbar'>
				<li id='0' class='active'>Upload<br>Code</li>
				<li id='1'>Select Lexer &<br>Theme</li>
				<li id='2'>Select Code<br>Formatter</li>
				<li id='3'>Export<br>Code</li>
			</ul>
		</div>
		<div id='step1-container' class='step-container show'>
			<input type='file' name='file' id='file' class='file-upload'>
			<button class='file-upload-btn' id='file-btn'>Choose File</button>
		</div>
		<div id='step2-container' class='step-container hide'>
			<select class='combobox' id='lexer-selector'>
				<option value='none'>Select Lexer</option>
				{% for lexer in lexer_list%}
					<option value='{{ lexer.1.0 }}'>{{ lexer.0 }}</option>
				{% endfor %}
			</select>
			<select class='combobox' id='style-selector'>
				<option value='none'>Select Theme</option>
				{% for style in style_list%}
					<option value='{{ style }}'>{{ style }}</option>
				{% endfor %}
			</select>
		</div>
		<div id='step3-container' class='step-container hide'>
			Coming Soon. Just proceed to next step =)
		</div>
		<div id='step4-container' class='step-container hide'>
			<a href='' id='file-download-btn' class='file-download-btn'>Download File</a>
		</div>
		<button type='submit' name='submit' id='submit' class='submit-btn'><span data-feather='chevron-right'></span></button>
		
	</div>
	<div class='previews-container'>
		{% for theme in preview %}
			<iframe src='{% url "code-syntax-highlight:get-preview" theme=theme %}' class='preview-frame'></iframe>
		{% endfor %}
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript">
		var current_step = 1;
		var can_proceed = false;
		$('#file-btn').on('click', function() {
		    $('#file').trigger('click')
		});
		$("#file").change(function() {
		    $("#file-btn").text(this.files[0].name);
		    can_proceed = true
		});
		$('#submit').on('click', function() {
		    if (current_step < 5 && can_proceed) {
		        $('.progressbar').children('#' + current_step.toString()).addClass('active');
		        $('#step' + (current_step).toString() + '-container').removeClass('show').addClass('hide');
		        current_step++;
		        $('#step' + (current_step).toString() + '-container').addClass('show');
		        if (current_step == 4) {
		            var file = document.getElementById('file').files[0];
		            if (file) {
		                var reader = new FileReader();
		                reader.readAsText(file, "UTF-8");
		                reader.onload = function(evt) {
		                    $.ajax({
		                        url: './get-formatted-code',
		                        type: 'POST',
		                        data: {
		                            'text': evt.target.result,
		                            'lexer': document.getElementById('lexer-selector').value,
		                            'style': document.getElementById('style-selector').value
		                        },
		                        success: function(data) {
		                            window.URL = window.webkitURL || window.URL;
		                            var file = new Blob([data])
		                            var a = document.getElementById('file-download-btn');
		                            a.href = window.URL.createObjectURL(file);
		                            a.download = document.getElementById('file').files[0].name + '.html';
		                            document.getElementById('submit').style.display = 'none'
		                        }
		                    })
		                }
		                reader.onerror = function(evt) {
		                    console.log("error reading file");
		                }
		            }
		        }
		    }
		})
	</script>
	<script type="text/javascript">
		feather.replace()
	</script>
</body>
</html>